services:
  backend:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      - PORT=5001

